export const SET_SORT_BY = 'SET_SORT_BY'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_ORDER_DIRECTION = 'SET_ORDER_DIRECTION'

export const SET_PIZZAS = 'SET_PIZZAS'
export const SET_LOADING = 'SET_LOADING'